### ISSUE TITLE
Can I please have the examples for LOB data types (Bytea, Text) in PostgreSQL

### ISSUE THREAD

**Issue by naveenjul29** [MattGson/Gybson#9]
Can you please help me with the examples for LOB data types (Bytea, Text) in PostgreSQL. Also need help in testing those exmaples?

I am sorry if it is not the right group to contact. If possible, can you please help me with right group who can help me on this?

Thanks in advance.

**Comment by lfa9603** [comment]
Unfortunately PostrgeSQL is not supported right now, refer to issue #2 to be updated as soon as we have this running. 

Regarding the LOB data types: due to the early stage of the project, we are currently not foreseeing to add this functionality in the near future. However, as soon as issue #4 is resolved, you are more than welcome to contribute to Gybson and add this functionality. We used schemats (https://www.npmjs.com/package/schemats) as inspiration to generate the TS interfaces for the schemas.
